target 'Up+' do
use_frameworks!
  pod 'SendBirdSDK'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'AFNetworking', '~> 3.0'
end
