# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Up+' do
use_frameworks!

pod 'SendBirdSDK'
pod 'AFNetworking'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
end
